# Generated by Django 4.1.4 on 2025-04-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Duyuru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Baslik", models.CharField(blank=True, max_length=200, null=True)),
                ("Aciklama", models.TextField(blank=True, null=True)),
                (
                    "Resim",
                    models.ImageField(
                        blank=True, null=True, upload_to="djangouploads/news"
                    ),
                ),
            ],
        ),
    ]
