# Generated by Django 4.1.4 on 2025-04-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_duyuru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duyuru",
            name="Resim",
            field=models.ImageField(
                blank=True, null=True, upload_to="djangouploads/duyurular"
            ),
        ),
    ]
