# Generated by Django 4.1.4 on 2025-04-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeclisDokumani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=255)),
                ("tarih", models.DateField()),
                (
                    "dosya",
                    models.FileField(
                        blank=True, null=True, upload_to="meclis_dokumanlari/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Meclis Dökümanı",
                "verbose_name_plural": "Meclis Dökümanları",
                "ordering": ["-tarih"],
            },
        ),
    ]
