# Generated by Django 4.1.4 on 2025-04-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_meclisdokumani"),
    ]

    operations = [
        migrations.RemoveField(model_name="haber", name="Resim2",),
        migrations.RemoveField(model_name="haber", name="Resim3",),
        migrations.AddField(
            model_name="haber",
            name="ana_haber",
            field=models.BooleanField(default=False),
        ),
    ]
