# Generated by Django 4.1.4 on 2025-04-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0004_alter_bagis_resim"),
    ]

    operations = [
        migrations.CreateModel(
            name="Burs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField()),
                ("tc", models.CharField(max_length=11)),
                ("isimsoyisim", models.CharField(max_length=100)),
                ("miktar", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
