# Generated by Django 4.1.4 on 2025-03-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Baslik", models.CharField(blank=True, max_length=200, null=True)),
                ("Aciklama", models.TextField(blank=True, null=True)),
                (
                    "Resim",
                    models.ImageField(
                        blank=True, null=True, upload_to="djangouploads/mainActivities"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MainPageInner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("biz_kimiz", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
