# Generated by Django 4.1.4 on 2025-04-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationalUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Birim Adı")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_units",
                        to="company.organizationalunit",
                        verbose_name="Üst Birim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizasyon Birimi",
                "verbose_name_plural": "Organizasyon Birimleri",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Ad Soyad"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Unvan"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        to="company.organizationalunit",
                        verbose_name="Bağlı Birim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sorumlu Kişi",
                "verbose_name_plural": "Sorumlu Kişiler",
            },
        ),
    ]
